name: Bug
description: Something is broken or behaving unexpectedly
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What went wrong?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      value: |
        1. 
        2. 
        3. 
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behaviour
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behaviour
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      description: "e.g. browser, OS, app version"
